name: Unit Tests

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin' # Specify the required Java distribution

    - name: Navigate to Project Directory
      run: cd Assignment2 # Ensure the directory path is correct

    - name: Install Dependencies
      run: mvn install

    - name: Run Tests
      run: mvn test
