name: Unit Tests

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Navigate to Project Directory
      run: cd Assignment2

    - name: Install Dependencies
      run: |
        cd Assignment2
        mvn install

    - name: Run Tests
      run: |
        cd Assignment2
        mvn test

